export const SECTORS = [
  {
    id: 'tech',
    name: 'Information Technology',
    short: 'Tech',
    etf: 'XLK',
    relatedEtfs: ['QQQ', 'IGV', 'SOXX'],
    color: '#4a8fd4',
    weight: 31.4,
    top7: ['AAPL', 'MSFT', 'NVDA', 'AVGO', 'ORCL', 'CRM', 'AMD'],
  },
  {
    id: 'financials',
    name: 'Financials',
    short: 'Financials',
    etf: 'XLF',
    relatedEtfs: ['KBE', 'KRE', 'IAI'],
    color: '#1fb87a',
    weight: 13.2,
    top7: ['BRK-B', 'JPM', 'V', 'MA', 'BAC', 'WFC', 'GS'],
  },
  {
    id: 'health',
    name: 'Health Care',
    short: 'Health Care',
    etf: 'XLV',
    relatedEtfs: ['IBB', 'XBI', 'IHI'],
    color: '#e8a835',
    weight: 11.8,
    top7: ['LLY', 'UNH', 'JNJ', 'ABBV', 'MRK', 'TMO', 'ABT'],
  },
  {
    id: 'consumer_disc',
    name: 'Consumer Discretionary',
    short: 'Cons. Disc.',
    etf: 'XLY',
    relatedEtfs: ['RTH', 'XRT', 'IBUY'],
    color: '#9b7de0',
    weight: 10.5,
    top7: ['AMZN', 'TSLA', 'HD', 'MCD', 'NKE', 'LOW', 'SBUX'],
  },
  {
    id: 'industrials',
    name: 'Industrials',
    short: 'Industrials',
    etf: 'XLI',
    relatedEtfs: ['ITA', 'JETS', 'PAVE'],
    color: '#d4507a',
    weight: 8.7,
    top7: ['GE', 'CAT', 'RTX', 'HON', 'UNP', 'BA', 'LMT'],
  },
  {
    id: 'comms',
    name: 'Communication Services',
    short: 'Comm. Svcs.',
    etf: 'XLC',
    relatedEtfs: ['IYZ', 'FCOM', 'SOCL'],
    color: '#4ab8b8',
    weight: 8.4,
    top7: ['META', 'GOOGL', 'NFLX', 'DIS', 'TMUS', 'VZ', 'CHTR'],
  },
  {
    id: 'staples',
    name: 'Consumer Staples',
    short: 'Cons. Staples',
    etf: 'XLP',
    relatedEtfs: ['VDC', 'FSTA', 'KXI'],
    color: '#a0c878',
    weight: 5.9,
    top7: ['WMT', 'PG', 'COST', 'KO', 'PEP', 'PM', 'MDLZ'],
  },
  {
    id: 'energy',
    name: 'Energy',
    short: 'Energy',
    etf: 'XLE',
    relatedEtfs: ['OIH', 'XOP', 'AMLP'],
    color: '#e07840',
    weight: 3.8,
    top7: ['XOM', 'CVX', 'COP', 'EOG', 'SLB', 'MPC', 'PSX'],
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    short: 'Real Estate',
    etf: 'XLRE',
    relatedEtfs: ['VNQ', 'IYR', 'REZ'],
    color: '#88b04b',
    weight: 2.4,
    top7: ['PLD', 'AMT', 'EQIX', 'WELL', 'SPG', 'DLR', 'O'],
  },
  {
    id: 'materials',
    name: 'Materials',
    short: 'Materials',
    etf: 'XLB',
    relatedEtfs: ['GDX', 'LIT', 'PICK'],
    color: '#c97f3e',
    weight: 2.2,
    top7: ['LIN', 'APD', 'SHW', 'FCX', 'ECL', 'NEM', 'NUE'],
  },
  {
    id: 'utilities',
    name: 'Utilities',
    short: 'Utilities',
    etf: 'XLU',
    relatedEtfs: ['VPU', 'IDU', 'FUTY'],
    color: '#6bb5c9',
    weight: 2.0,
    top7: ['NEE', 'SO', 'DUK', 'AEP', 'SRE', 'D', 'EXC'],
  },
]

export const SP_SECTORS = SECTORS.map(s => ({
  name: s.short,
  pct: s.weight,
  color: s.color,
}))

export const TICKER_COLORS = [
  '#4a8fd4', '#1fb87a', '#e8a835', '#e05050',
  '#9b7de0', '#d4507a', '#4ab8b8',
]
